# These are supported funding model platforms

github: [vitalybibikov]  # Replace with your GitHub sponsor username if available

# Uncomment and replace with your Patreon username if you have one
# patreon: <your_username>

# Uncomment and replace with your Open Collective username if you have one
# opencollective: <your_username>

# Uncomment and replace with your Ko-fi username if you have one
# ko_fi: <your_username>

# Uncomment and replace with your Tidelift username if you have one
# tidelift: <your_package>

# Uncomment and replace with your Community Bridge project name if you have one
# community_bridge: <your_project>

# Uncomment and replace with your Liberapay username if you have one
# liberapay: <your_username>

# Uncomment and replace with your IssueHunt username if you have one
# issuehunt: <your_username>

# Uncomment and replace with your Otechie username if you have one
# otechie: <your_username>

# Uncomment and replace with your custom link if you have one
# custom: ['https://www.example.com/donate']
