version: '3.9'

services:
  tests:
    image: ${DOCKER_REGISTRY-}tests
    build:
      context: .
      dockerfile: ./test/DynamoDBv2.Transactions.IntegrationTests/Dockerfile
    depends_on:
      - localstack
  unittests:
    image: ${DOCKER_REGISTRY-}tests
    build:
      context: .
      dockerfile: ./test/DynamoDBv2.Transactions.UnitTests/Dockerfile

  localstack:
    container_name: localstack
    image: localstack/localstack:latest