version: '3.9'

services:
  tests:
    image: ${DOCKER_REGISTRY-}tests
    build:
      context: .
      dockerfile: ./test/DynamoDBv2.Transactions.IntegrationTests/Dockerfile
    depends_on:
      - localstack
  unittests:
    image: ${DOCKER_REGISTRY-}unittests
    build:
      context: .
      dockerfile: ./test/DynamoDBv2.Transactions.UnitTests/Dockerfile
  benchmarks:
     image: ${DOCKER_REGISTRY-}benchmarks
     build:
        context: .
        dockerfile: ./test/DynamoDBv2.Transactions.Benchmarks/Dockerfile
     depends_on:
       - localstack
  localstack:
    container_name: localstack
    image: localstack/localstack:latest