name: CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.override.yml config
          docker-compose pull
          docker-compose build

      - name: Run tests
        run: docker-compose up --exit-code-from tests

      - name: Upload TRX test results
        uses: actions/upload-artifact@v2
        if: always()  # This ensures it runs even if the previous steps fail
        with:
          name: trx-test-results
          path: ./test-results/*.trx

      - name: Clean up
        run: docker-compose down
        
      - name: Parse Trx files
        uses: NasAmin/trx-parser@v0.5.0
        id: trx-parser
        with:
          TRX_PATH: ${{ github.workspace }}/test-results #This should be the path to your TRX files
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
