name: CI

permissions:
    contents: read
    pull-requests: write # required if create-pr-comment: true
    checks: write       # required if create-status-check: true

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.override.yml config
          docker-compose pull
          docker-compose build

      - name: Run tests
        run: docker-compose up --exit-code-from tests

      - name: Upload TRX test results
        uses: actions/upload-artifact@v2
        if: always()  # This ensures it runs even if the previous steps fail
        with:
          name: trx-test-results
          path: ./test-results/*.trx

      - name: Clean up
        run: docker-compose down
        
      - name: Parse Trx files
        uses: NasAmin/trx-parser@v0.5.0
        id: trx-parser
        with:
          TRX_PATH: ${{ github.workspace }}/test-results #This should be the path to your TRX files
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}  


      - name: Process trx reports
        id: process-trx
        # You may also reference just the major or major.minor version
        uses: im-open/process-dotnet-test-results@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-directory: './test-results'
          create-status-check: true
          create-pr-comment: true
          update-comment-if-one-exists: true
          ignore-test-failures: true
          timezone: 'america/denver'
          comment-identifier: 'bff-tests'

      # Optional
      - name: Annotate Test Outcome
        if: steps.process-trx.outputs.test-results-truncated == 'true'
        run: cat ${{ steps.process-trx.outputs.test-results-file-path }} > $GITHUB_STEP_SUMMARY

      # Optional
      - name: Upload Outcome as artifact if character limit reached
        if: steps.process-trx.outputs.test-results-truncated == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Cypress-Results
          path: |
            ${{ steps.process-trx.outputs.test-results-file-path }}
          retention-days: 90

