name: CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.override.yml config
          docker-compose pull
          docker-compose build

      - name: Run tests
        run: docker-compose up --exit-code-from tests

      - name: Upload TRX test results
        uses: actions/upload-artifact@v2
        if: always()  # This ensures it runs even if the previous steps fail
        with:
          name: trx-test-results
          path: ./test-results/*.trx

      - name: Clean up
        run: docker-compose down
        
      - name: Integration Tests for DynamoDB Transactions
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: ./test-results/
          report_name: testresults.trx
          report_title: Integration Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: contoso_business_tests.md
          gist_badge_label: 'Contoso Business: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
